chore: Python ingress changes
twilio/twilio-oai-generator pull request #548
Opened 2023-11-29 10:35 UTC by tiwarishubham635

# Fixes #

A short description of what this PR does.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] Run `make test-docker`
- [ ] Verify affected language:
    - [ ] Generate [twilio-go](https://github.com/twilio/twilio-go) from our [OpenAPI specification](https://github.com/twilio/twilio-oai) using the [build_twilio_go.py](./examples/build_twilio_go.py) using `python examples/build_twilio_go.py path/to/twilio-oai/spec/yaml path/to/twilio-go` and inspect the diff
    - [ ] Run `make test` in `twilio-go`
    - [ ] Create a pull request in `twilio-go`
    - [ ] Provide a link below to the pull request
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-oai-generator/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please create a GitHub Issue in this repository.

2023-12-05 08:23 UTC, manisha1997 requested changes

2023-12-05 08:27 UTC, tiwarishubham635 commented on src/test/java/com/twilio/oai/TwilioGeneratorTest.java
> +//        final String pathname = "/Users/stiwari/di/github/twilio-oai/spec/yaml/twilio_messaging_bulk_v1.yaml";
Oh yeah, I will remove them

2023-12-05 08:29 UTC, manisha1997 requested changes

2023-12-05 08:29 UTC, manisha1997 commented on src/main/java/com/twilio/oai/resolver/python/PythonCodegenModelContainerDataTypeResolver.java
> +public class PythonCodegenModelContainerDataTypeResolver extends CodegenModelContainerDataTypeResolver {
Add javadoc

2023-12-05 08:30 UTC, manisha1997 requested changes

2023-12-05 08:30 UTC, manisha1997 commented on src/main/java/com/twilio/oai/resolver/python/PythonCodegenModelDataTypeResolver.java
> +public class PythonCodegenModelDataTypeResolver extends CodegenModelDataTypeResolver {
https://github.com/twilio/twilio-oai-generator/pull/548#discussion_r1415125682

2023-12-05 08:30 UTC, manisha1997 commented on src/main/java/com/twilio/oai/resolver/python/PythonCodegenModelResolver.java
> +public class PythonCodegenModelResolver extends CodegenModelResolver {
https://github.com/twilio/twilio-oai-generator/pull/548#discussion_r1415125682

2023-12-14 07:17 UTC, kridai approved these changes

2023-12-14 07:19 UTC, shrutiburman approved these changes

2023-12-14 07:42 UTC, tiwarishubham635 commented
C# tests are failing as sonar requires minimum java 17 version. See [this](https://docs.sonarsource.com/sonarqube/latest/requirements/prerequisites-and-overview/)

2023-12-14 07:49 UTC, merged